check-patch:
  extends: .job_rules
  stage: build
  image: $CI_REGISTRY_IMAGE/qemu/centos8:latest
  needs:
    job: amd64-centos8-container
  script:
    - .gitlab-ci.d/check-patch.py
  variables:
    QEMU_JOB_MINIMAL: 1
    GIT_DEPTH: 1000
  allow_failure: true

check-dco:
  extends: .job_rules
  stage: build
  image: $CI_REGISTRY_IMAGE/qemu/centos8:latest
  needs:
    job: amd64-centos8-container
  script: .gitlab-ci.d/check-dco.py
  variables:
    QEMU_JOB_MINIMAL: 1
    GIT_DEPTH: 1000

check-python-pipenv:
  extends: .job_rules
  stage: test
  image: $CI_REGISTRY_IMAGE/qemu/python:latest
  script:
    - make -C python check-pipenv
  variables:
    QEMU_JOB_MINIMAL: 1
    GIT_DEPTH: 1
  needs:
    job: python-container

check-python-tox:
  extends: .job_rules
  stage: test
  image: $CI_REGISTRY_IMAGE/qemu/python:latest
  script:
    - make -C python check-tox
  variables:
    QEMU_JOB_MINIMAL: 1
    GIT_DEPTH: 1
    QEMU_TOX_EXTRA_ARGS: --skip-missing-interpreters=false
  needs:
    job: python-container
  allow_failure: true
