# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-patch:
    name: Check Patch
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependent packages
        run: sudo apt install perl
      - name: Checkpatch
        run: |
          git fetch https://git.qemu.org/git/qemu.git master
          git tag base_tag_to_rebase FETCH_HEAD --force
          ./scripts/checkpatch.pl --mailback base_tag_to_rebase..
